# Generated by Django 4.2.27 on 2026-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('middle_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('mobile', models.CharField(max_length=15)),
                ('village', models.CharField(max_length=128)),
                ('subdistrict', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
            ],
        ),
    ]
