# Generated by Django 4.2.27 on 2026-01-13 14:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('shared', 'Shared Room'), ('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('pg', 'PG Room')], max_length=50)),
                ('flat_system', models.CharField(choices=[('entire', 'Entire Flat'), ('room', 'Only Room'), ('pg', 'PG System')], max_length=50)),
                ('city', models.CharField(default='', max_length=100)),
                ('area_location', models.CharField(default='', max_length=200)),
                ('full_address', models.TextField(default='')),
                ('monthly_rent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('security_deposit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_charges', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('per_person_rent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('main_image', models.ImageField(default='property_images/default.jpg', upload_to='property_images/')),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('furnishing_status', models.CharField(choices=[('fully', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=50)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('nearby_college_office', models.CharField(blank=True, max_length=200, null=True)),
                ('nearby_mall', models.CharField(blank=True, max_length=200, null=True)),
                ('garden_park_nearby', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_medical', models.CharField(blank=True, max_length=200, null=True)),
                ('temple_religious', models.CharField(blank=True, max_length=200, null=True)),
                ('bus_railway_distance', models.CharField(blank=True, max_length=200, null=True)),
                ('mess_available', models.BooleanField(default=False)),
                ('mess_type', models.CharField(blank=True, choices=[('veg', 'Veg'), ('nonveg', 'Non-Veg'), ('both', 'Both')], max_length=50, null=True)),
                ('mess_distance', models.CharField(blank=True, max_length=200, null=True)),
                ('tiffin_available', models.BooleanField(default=False)),
                ('preferred_tenant_type', models.CharField(choices=[('students', 'Students'), ('professionals', 'Working Professionals'), ('family', 'Family')], max_length=100)),
                ('gender_preference', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=50)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('drinking_allowed', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('available_from', models.DateField(default='2024-01-01')),
                ('min_stay_duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'Tenant'), ('homeowner', 'Home Owner')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('subdistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='myapp.property')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('owner_response', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='myapp.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('property', 'tenant')},
            },
        ),
    ]
