# Generated by Django 4.2.27 on 2026-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Property latitude', max_digits=9),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Property longitude', max_digits=9),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
